### ISSUE TITLE
Failed to start the Strapi server

### ISSUE THREAD

**Issue by viswongdev** [strapi/strapi-tutorials#18]
I followed the readme and ran these command

`cd tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend && yarn && strapi dev`

it said no strapi dev command found, then I read the npm script and run script "`develop`"

[2020-01-30T10:34:30.524Z] debug ⛔️ Server wasn't able to start properly.
[2020-01-30T10:34:30.526Z] error Error: Cannot find module 'stripe'
Require stack:
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/api/order/controllers/Order.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/load/load-files.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/load/load-config-files.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/core/load-config.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/core/index.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/Strapi.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/index.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/lib/commands/develop.js
- /Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/git/Desktop/git/strapi-tutorials/tutorials/deliveroo-clone-nuxt-strapi-tutorial/backend/api/order/controllers/Order.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/git/.npm/_logs/2020-01-30T10_34_30_535Z-debug.log

**Comment by Mcastres** [comment]
Hello @viswongdev !

In fact, stripe was missing in the `package.json`.
I added it in the last commit, but if you want to fix it locally:

  - Run `yarn add stripe` or `npm install stripe`
