### ISSUE TITLE
BUG - GraphQL error: Forbidden

### ISSUE THREAD

**Issue by JurajJakubov** [strapi/strapi-tutorials#20]
Hello,

i cloned this repo https://github.com/strapi/strapi-tutorials/tree/master/tutorials/next-strapi-apollo-blog then run commands but in the end i am getting error in frontend.

This is website 
```
Error: {"graphQLErrors":[{"message":"Forbidden","locations":[{"line":2,"column":3}],"path":["categories"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Forbidden"},"headers":{}},"message":"Forbidden","stacktrace":["Error: Forbidden"," at handleErrors (C:\\Users\\jakub\\Downloads\\strapi-tutorials-master\\strapi-tutorials-master\\tutorials\\next-strapi-apollo-blog\\backend\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:116:54)"," at module.exports (C:\\Users\\jakub\\Downloads\\strapi-tutorials-master\\strapi-tutorials-master\\tutorials\\next-strapi-apollo-blog\\backend\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:100:12)"]}}}],"networkError":null,"message":"GraphQL error: Forbidden"}

Strapi blog
Error: {"graphQLErrors":[{"message":"Forbidden","locations":[{"line":2,"column":3}],"path":["articles"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Forbidden"},"headers":{}},"message":"Forbidden","stacktrace":["Error: Forbidden"," at handleErrors (C:\\Users\\jakub\\Downloads\\strapi-tutorials-master\\strapi-tutorials-master\\tutorials\\next-strapi-apollo-blog\\backend\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:116:54)"," at module.exports (C:\\Users\\jakub\\Downloads\\strapi-tutorials-master\\strapi-tutorials-master\\tutorials\\next-strapi-apollo-blog\\backend\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:100:12)"]}}}],"networkError":null,"message":"GraphQL error: Forbidden"}
```

And this is console.
```
null
GraphQL error occurred [getDataFromTree] { Error: GraphQL error: Forbidden
    at new ApolloError (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:92:26)
    at C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:1587:34
    at C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:2007:15
    at Set.forEach (<anonymous>)
    at C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:2005:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:2003:20) 
    at C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:2130:19
    at Object.next (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\zen-observable\lib\Observable.js:322:23)
    at notifySubscription (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\zen-observable\lib\Observable.js:135:18)        
    at onNotify (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.next (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\zen-observable\lib\Observable.js:235:7)  
    at C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:1101:36
    at Set.forEach (<anonymous>)
    at Object.next (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\apollo-client\bundle.umd.js:1100:21)
    at notifySubscription (C:\Users\jakub\Downloads\strapi-tutorials-master\strapi-tutorials-master\tutorials\next-strapi-apollo-blog\frontend\node_modules\zen-observable\lib\Observable.js:135:18)        
  graphQLErrors:
   [ { message: 'Forbidden',
       locations: [Array],
       path: [Array],
       extensions: [Object] } ],
  networkError: null,
  message: 'GraphQL error: Forbidden',
  extraInfo: undefined }
null
```

Thanks for any help with this issue.
Node.js version:
v10.13.0
npm version:
6.13.6
Operating system:
OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.18363 N/A Build 18363

**Comment by Mcastres** [comment]
Hello @JurajJakubov!
It's completely normal, by default the permissions to interact with your data (find, create, update, delete etc...) are not activated for security purposes.

You'll need to activate them in Roles & Permissions > Public > Article/Category (find and findone)
